version: "3.8"

services:
  app:
    build:
      context: .
        dockerfile:Dockerfile
    container_name: anifit_space
    port:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
