import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import { getServerSession } from "next-auth";
import SessionProvider from "@/provider/session-provider";
import ThemeProvider from "@/provider/theme-provider";
import { cn } from "@/lib/utils";
import "./globals.css";
// import { Session } from "inspector";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  console.log(session);
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable,
        )}
      >
        <ThemeProvider>
          <SessionProvider session={session}>{children}</SessionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
